name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  

    runs-on: ${{ matrix.os }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable 

      - name: Install dependencies
        run: |
          cargo fetch

      - name: Build project
        run: |
          cargo build --release

      - name: Run tests
        run: |
          cargo test
